package example.ibatis.dao.mysql.dao;

import example.ibatis.dao.mysql.model.StudentDo;
import example.ibatis.dao.mysql.model.StudentDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student
     *
     * @mbggenerated
     */
    int countByExample(StudentDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student
     *
     * @mbggenerated
     */
    int deleteByExample(StudentDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student
     *
     * @mbggenerated
     */
    int insert(StudentDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student
     *
     * @mbggenerated
     */
    int insertSelective(StudentDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student
     *
     * @mbggenerated
     */
    List<StudentDo> selectByExample(StudentDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student
     *
     * @mbggenerated
     */
    StudentDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StudentDo record, @Param("example") StudentDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StudentDo record, @Param("example") StudentDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StudentDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StudentDo record);
}