package example.ibatis.dao.mysql.dao;

import example.ibatis.dao.mysql.model.StudentSubjectDo;
import example.ibatis.dao.mysql.model.StudentSubjectDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentSubjectDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student_subject
     *
     * @mbggenerated
     */
    int countByExample(StudentSubjectDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student_subject
     *
     * @mbggenerated
     */
    int deleteByExample(StudentSubjectDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student_subject
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student_subject
     *
     * @mbggenerated
     */
    int insert(StudentSubjectDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student_subject
     *
     * @mbggenerated
     */
    int insertSelective(StudentSubjectDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student_subject
     *
     * @mbggenerated
     */
    List<StudentSubjectDo> selectByExample(StudentSubjectDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student_subject
     *
     * @mbggenerated
     */
    StudentSubjectDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student_subject
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StudentSubjectDo record, @Param("example") StudentSubjectDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student_subject
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StudentSubjectDo record, @Param("example") StudentSubjectDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student_subject
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StudentSubjectDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_student_subject
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StudentSubjectDo record);
}