package example.ibatis.dao.mysql.dao;

import example.ibatis.dao.mysql.model.UserDo;
import example.ibatis.dao.mysql.model.UserDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_user
     *
     * @mbggenerated
     */
    int countByExample(UserDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_user
     *
     * @mbggenerated
     */
    int deleteByExample(UserDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_user
     *
     * @mbggenerated
     */
    int insert(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_user
     *
     * @mbggenerated
     */
    int insertSelective(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_user
     *
     * @mbggenerated
     */
    List<UserDo> selectByExample(UserDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_user
     *
     * @mbggenerated
     */
    UserDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserDo record, @Param("example") UserDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserDo record, @Param("example") UserDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserDo record);
}