package example.ibatis.dao.mysql.model;

import java.util.Date;

public class StudentSubjectDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ie_student_subject.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ie_student_subject.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ie_student_subject.modified_time
     *
     * @mbggenerated
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ie_student_subject.student_id
     *
     * @mbggenerated
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ie_student_subject.subject_name
     *
     * @mbggenerated
     */
    private String subjectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ie_student_subject.subject_teacher
     *
     * @mbggenerated
     */
    private String subjectTeacher;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ie_student_subject.id
     *
     * @return the value of ie_student_subject.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ie_student_subject.id
     *
     * @param id the value for ie_student_subject.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ie_student_subject.create_time
     *
     * @return the value of ie_student_subject.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ie_student_subject.create_time
     *
     * @param createTime the value for ie_student_subject.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ie_student_subject.modified_time
     *
     * @return the value of ie_student_subject.modified_time
     *
     * @mbggenerated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ie_student_subject.modified_time
     *
     * @param modifiedTime the value for ie_student_subject.modified_time
     *
     * @mbggenerated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ie_student_subject.student_id
     *
     * @return the value of ie_student_subject.student_id
     *
     * @mbggenerated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ie_student_subject.student_id
     *
     * @param studentId the value for ie_student_subject.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ie_student_subject.subject_name
     *
     * @return the value of ie_student_subject.subject_name
     *
     * @mbggenerated
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ie_student_subject.subject_name
     *
     * @param subjectName the value for ie_student_subject.subject_name
     *
     * @mbggenerated
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ie_student_subject.subject_teacher
     *
     * @return the value of ie_student_subject.subject_teacher
     *
     * @mbggenerated
     */
    public String getSubjectTeacher() {
        return subjectTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ie_student_subject.subject_teacher
     *
     * @param subjectTeacher the value for ie_student_subject.subject_teacher
     *
     * @mbggenerated
     */
    public void setSubjectTeacher(String subjectTeacher) {
        this.subjectTeacher = subjectTeacher == null ? null : subjectTeacher.trim();
    }
}